# Generated by Django 5.0.7 on 2024-07-20 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Долгота')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2, verbose_name='Зима')),
                ('spring_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2, verbose_name='Весна')),
                ('summer_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2, verbose_name='Лето')),
                ('autumn_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2, verbose_name='Осень')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=128, verbose_name='Тип объекта')),
                ('title', models.CharField(max_length=128, verbose_name='Название объекта')),
                ('other_titles', models.CharField(max_length=128, verbose_name='Другое название')),
                ('connect', models.CharField(max_length=128, verbose_name='Подключение')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('NW', 'новый'), ('PN', 'модератор взял в работу'), ('AC', 'модерация прошла успешно'), ('RJ', 'модерация прошла, информация не принята')], default='NW', max_length=2, verbose_name='Статус записи')),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level', verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='Электронная почта')),
                ('fam', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('pat', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='coord',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perevalimage',
            name='pereval',
        ),
        migrations.DeleteModel(
            name='PerevalArea',
        ),
        migrations.DeleteModel(
            name='SprActivitiesType',
        ),
        migrations.AddField(
            model_name='images',
            name='pereval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users', verbose_name='Турист'),
        ),
        migrations.DeleteModel(
            name='Coord',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='PerevalAdded',
        ),
        migrations.DeleteModel(
            name='PerevalImage',
        ),
    ]
