# Generated by Django 5.0.7 on 2024-07-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_pereval_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='coord_id',
            new_name='coord',
        ),
    ]
