# Generated by Django 5.0.7 on 2024-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_rename_coord_id_pereval_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn_lev',
            field=models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='3A', max_length=2, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring_lev',
            field=models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='2A', max_length=2, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer_lev',
            field=models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='1A', max_length=2, verbose_name='Лето'),
        ),
    ]
