# Generated by Django 5.0.7 on 2024-07-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0006_alter_level_autumn_lev_alter_level_spring_lev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn_lev',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='3A', max_length=2, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring_lev',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='2A', max_length=2, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer_lev',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='1A', max_length=2, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter_lev',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('4A', '4A')], default='4A', max_length=2, verbose_name='Зима'),
        ),
    ]
