# Generated by Django 5.0.7 on 2024-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_level_autumn_lev_alter_level_spring_lev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(choices=[('connection', 'Connection'), ('disconnect', 'Disconnect'), ('unstable connection', 'Unstable Connection')], max_length=32, verbose_name='Подключение'),
        ),
    ]
